name: rubricai_ai

services:
  python_rag:
    build: ./rubricai_ai
    container_name: python_rag
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./rubricai_ai:/app
      - hf_cache:/root/.cache/huggingface

  frontend:
    build: ./frontend
    container_name: astro_frontend
    restart: unless-stopped
    ports:
      - "4321:4321"
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - python_rag

volumes:
  hf_cache:
